### ISSUE TITLE
Soporte para stickers en registro de mensajes

### ISSUE THREAD

**Issue by gmm96** [alvarogzp/telegram-bot#87]
Mételo joputa, que guarde el id del sticker y del paquete o algo, que te reviento.

**Comment by gboquizosanchez** [comment]
xDDDDDDDDDDD

**Comment by alvarogzp** [comment]
Hecho en la pull request #102, pruébalo XD

**Comment by alvarogzp** [comment]
También está el #92, el #68 y el #78
